# Generated by Django 3.2.6 on 2021-08-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jszc_info',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='id')),
                ('author', models.CharField(max_length=128, verbose_name='执行人')),
                ('taskName', models.CharField(max_length=255, verbose_name='任务名称')),
                ('department', models.CharField(max_length=255, verbose_name='部门')),
                ('projectName', models.CharField(max_length=255, verbose_name='项目名称')),
                ('created', models.DateTimeField(verbose_name='创建时间')),
                ('updated', models.DateTimeField(verbose_name='更新时间')),
                ('projectId', models.CharField(max_length=128, verbose_name='任务编号')),
            ],
        ),
        migrations.CreateModel(
            name='workitems',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.CharField(default=None, max_length=255, verbose_name='工作内容')),
                ('author', models.CharField(max_length=128, verbose_name='填写人')),
                ('idReadable', models.CharField(max_length=128, verbose_name='任务号')),
                ('duration', models.IntegerField(default=0, verbose_name='工作量')),
                ('created', models.DateTimeField(verbose_name='填写日期')),
            ],
        ),
    ]
